version: '2'

services:
  builder:
    image: golang:1.7
    working_dir: /go/src/github.com/lox/lifecycled
    environment:
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - "..:/go/src/github.com/lox/lifecycled"